<a href="https://colab.research.google.com/github/Aravind-Reddy7/ML-Course/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
import numpy as np

In [ ]:
mylist = [1, 2, 3]

In [ ]:
mylist

[1, 2, 3]

In [ ]:
type(mylist)

list

In [ ]:
np.array(mylist)

array([1, 2, 3])

In [ ]:
myarr = np.array(mylist)

In [ ]:
myarr

array([1, 2, 3])

In [ ]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
type(my_matrix)

list

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
myarr_matrix = np.array(my_matrix)

In [ ]:
myarr_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(1, 101, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
len(np.linspace(0, 10, 5))

5

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5, 3)

array([[0.06137033, 0.19231406, 0.71426286],
       [0.63995857, 0.88214506, 0.07210321],
       [0.45499797, 0.07799571, 0.08555148],
       [0.2499282 , 0.57429565, 0.25305993],
       [0.41827839, 0.99924902, 0.26503097]])

In [ ]:
np.random.randn(10)

array([-1.43486456, -0.4022563 ,  1.31850971,  0.32460992, -0.59952831,
       -0.48496726,  0.36151019, -0.93108916, -0.21705854, -0.30839352])

In [ ]:
np.random.randn(2, 3)

array([[-9.37238474e-02,  3.43962180e-01, -1.82368647e-01],
       [-8.50127139e-01, -5.00293086e-04,  6.25284976e-01]])

In [ ]:
np.random.randint(1, 101, 10)

array([66, 65, 66, 99, 29, 75, 40, 39, 90, 10])

In [ ]:
np.random.seed(100)
np.random.rand(4)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613])

In [ ]:
np.random.seed(100)
np.random.rand(4)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613])

In [ ]:
np.random.rand(4)

array([0.00471886, 0.12156912, 0.67074908, 0.82585276])

In [ ]:
arr = np.arange(0, 25)
arr
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
array = np.random.randint(0, 101, 10)
array

array([ 2, 94, 19, 98, 63, 53, 27, 56, 30, 48])

In [ ]:
array.max()

98

In [ ]:
array.min()

2

In [ ]:
array.argmax()

3

In [ ]:
array.argmin()

0

In [ ]:
array.dtype

dtype('int64')

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(25, )

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [3]:
!pwd

/content


In [8]:
!mkdir folder1

In [6]:
import os

In [7]:
os.mkdir("folder2")

In [9]:
!mkdir '/content/drive/MyDrive/folder_1'

mkdir: cannot create directory ‘/content/drive/MyDrive/folder_1’: File exists


In [ ]:
os.mkdir('/content/drive/MyDrive/folder_1')